services:
  # gRPC Backend Service
  grpc-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: grpc-chat-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000  # Changed from http://localhost:5000
    networks:
      - chat-network

  # Vue.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: grpc-chat-frontend
    ports:
      - "3000:80"
    depends_on:
      - grpc-backend
    networks:
      - chat-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  chat-network:
    driver: bridge